name: Bug Report
description: Report a bug in ax-score
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command...
        2. With arguments...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Expected behavior..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What happens instead?
      placeholder: "Actual behavior..."
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: If applicable, paste the error message or stack trace
      render: shell

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area of ax-score is affected?
      options:
        - CLI
        - Gatherers
        - Audits
        - Reporter
        - Scoring
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ax-score Version
      description: What version of ax-score are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: "e.g., 20.0.0"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Any other relevant environment information
      placeholder: "OS, npm/pnpm version, etc."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem

  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct
          required: true
