name: Feature Request
description: Suggest an idea for ax-score
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it.
      placeholder: "Describe the problem or use case..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "Describe your proposed solution..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternative approaches..."

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area of ax-score would this feature affect?
      options:
        - CLI
        - Gatherers
        - Audits
        - Reporter
        - Scoring
        - Configuration
        - Web UI
        - CI/CD Integration
        - Plugin System
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or references

  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct
          required: true
